os:
  - linux
  - windows

compiler: gcc
language: cpp

before_install:
  - env
  - printenv
  - echo "$test"
  - env >/dev/null 2>&1
  - printenv >/dev/null 2>&1
  - echo "$test" >/dev/null 2>&1

install:
  - env
  - printenv
  - echo "$test"
  - env >/dev/null 2>&1
  - printenv >/dev/null 2>&1
  - echo "$test" >/dev/null 2>&1

script:
  - env
  - printenv
  - echo "$test"
  - env >/dev/null 2>&1
  - printenv >/dev/null 2>&1
  - echo "$test" >/dev/null 2>&1
