env:
  global:
    # tag
    - DEPLOY_RELEASE="0.19_pre"
    #
    - FREECAD_RELEASE="0.18"
    # - DEPLOY_RELEASE=${DEPLOY_RELEASE:-$FREECAD_RELEASE}
    - OSX_PORTS_CACHE=${OSX_PORTS_CACHE:-FreeCAD/FreeCAD-ports-cache}
    - DEPLOY_REPO=${DEPLOY_REPO:-FreeCAD/FreeCAD}
    - DEPLOY=${DEPLOY:-0}

os:
  # - linux
  # - osx
  - windows

compiler: gcc
language: cpp

before_install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-win-64.exe -O conda.exe --no-check-certificate;
      cmd.exe //C 'conda.exe create -y -q -p C:\conda conda conda-build=3.18.10 conda-verify python=3.7';
      cmd.exe //C 'call C:\conda\Scripts\activate';
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      cd conda/win_dev;
      cmd.exe //C 'win_dev.bat';
      cd ..;
    fi
